import Head from 'next/head'
import {signOut} from 'next-auth/react'
import Image from 'next/image'
export default function Home() {
  return (
    <div>
      <Head>
        <title>
          linkedin-clone
        </title>
        <meta name='description'content='Generated by michael Andom'/>
     <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={signOut}>signOut</button>
    </div>
  )
}
